### ISSUE TITLE
Failed: `redis_leader_z1/0 (xxx)' is not running after update

### ISSUE THREAD

**Issue by lummie** [cloudfoundry-community/redis-consul-boshrelease#1]
I'm getting Failed: `redis_leader_z1/0 (xxx)' is not running after update when I bosh deploy. I have tried increasing the canary and watch update times but even at 800,000 it makes no difference.

I know this is probably to do with my manifest configuration but the only "error" logs I can find that may hint a failure are as follows from the redis_leader_z1 vm (I'm deploying on AWS) :/var/vcap/sys/log/consul_agent/consul_agent.stderr.log:

++ logger -p user.info -t vcap.consul-agent
++ tee -a /var/vcap/sys/log/consul_agent/consul_agent.stdout.log
at least one "expected-member" must be provided

usage: confab COMMAND OPTIONS

COMMAND: "start" or "stop"

OPTIONS:
  -agent-path executable
        path to the on-filesystem consul executable
  -config-file file
..... shows the rest of the help output

Any ideas what may cause this ? 
I'd first deployed cloudfoundry-community/redis-boshrelease and this worked and then realised that this did not provide the cloud foundy service then moved over to deploying the redis-consul-boshrelease.

The manifest seems to be correct as far as my understanding goes. 
Any help greatly appreciated.

**Comment by drnic** [comment]
Closing as project moved to the attic
